name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_chat_app:
    name: Test Chat App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [ '12', '14' ]
    steps:
      - name: Install Fluvio Local Cluster
        uses: infinyon/fluvio@fix/action/fluvio/darwin
        with:
          cluster-type: local
          version: v0.6.0-alpha.3
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Chat Server & Run
        run: |
          pushd ./chat-app/chat-server
          npm install
          npm run start &
          popd
      - name: Install Chat Client
        run: |
          pushd ./chat-app/chat-client
          npm install
          npm run start &
          popd
      - name: Install and Run Tests
        run: |
          pushd ./chat-app
          npm install
          npx cypress run -b chrome --headless
          npm run test
          popd