name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_chat_app:
    name: Test Chat App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        node: [ '14' ]
    steps:
      - name: Install Fluvio Local Cluster
        uses: infinyon/fluvio@master
        with:
          cluster-type: local
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install & Run Test
        run: |
          pushd ./chat-app
          npm install
          
          pushd ./chat-server
          npm run start &
          popd

          pushd ./chat-client
          npm run start &
          popd

          npm run test